---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  ## default_auth is the name of config. This will be referred from volume mount definition
  mysql_database: "default"
  mysql_user: "amin"
  wordpress_user: "wordpress"
  default_auth: |
    [mysqld]
    default_authentication_plugin= mysql_native_password