apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  labels:
    app: mysql
type: Opaque
data:
  # This is base64 encoded -- the real password is 2!0r!!B2yrB0an!
  mysql_root_password: MiEwciEhQjJ5ckIwYW4hCg==
  # amin!amin56
  mysql_password: YW1pbiFhbWluNTYK
  # $DQc4$0z4R1byx$X22cl
  wordpress_password: JERRYzQkMHo0UjFieXgkWDIyY2wK
